### ISSUE TITLE
Gap property and magin fallback appearing at the same time

### ISSUE THREAD

**Issue by gorkamolero** [ppiyush13/react-styled-flex#36]
Hey there team!

Your component's great. I've been using it in a few projects with great success.

However, I've found an issue with gap & margin

In my team most people use mac. There's one person using Windows and Chrome. in her case, the gap property is being applied but every child gets a ':not(:last-child)' **margin** property too. We believe it's not evaluating well if the gap property is supported on this Window browser.

Would you take a look at this? Please let me know.

All the best

**Comment by ppiyush13** [comment]
Hello @gorkamolero !

Seems like you have hit the edge scenarios. Please can you share some more information like OS version, browser version, your app setup, etc. Also are you using this in SSR mode ?

**Comment by gorkamolero** [comment]
Hello and thanks for the prompt response @ppiyush13 !

No SSR. We're using Clutch.io to build the app, which could be the culprit! Apparently the issue comes and goes.

As for the rest of the setup, it's just a simple Windows:
Windows 10 Home v 20H2
 Chrome Versión 88.0.4324.182 (Official build) (64 bits)

**Comment by ppiyush13** [comment]
@gorkamolero I had a chat with clutch.io tech support, and they have confirmed that clutch.io is based on SSR. So that's why you are facing above issue. I am working on version 2 of `react-styled-flex`, which intends to make it compatible with SSR rendering.  You may track #35.

**Comment by gorkamolero** [comment]
I didn't realize about the lack of SSR support! Sorry. Do you have a timeline on this? I'm actually using it for a project that will indeed use SSR

**Comment by ppiyush13** [comment]
No problem @gorkamolero . I am planning to release new version by 7th of March. I will notify here whenever I release.

**Comment by ppiyush13** [comment]
Hi @gorkamolero, apologies for late reply, was caught in some other work. Would you please try new version `react-styled-flex@2.0.0-rc.1` . I have applied fixes to work in SSR and SSG mode. Kindly provide feedback.

**Comment by gorkamolero** [comment]
Hello! I completely missed this message. I'll try your latest version today @ppiyush13 . Thank you for all the work

**Comment by gorkamolero** [comment]
Hey @ppiyush13 having trouble passing down props to this new version. Is it restricting some types of props somehow?

**Comment by ppiyush13** [comment]
Hey @gorkamolero exactly what errors are you getting ?

**Comment by gorkamolero** [comment]
I'll try again soon

**Comment by gorkamolero** [comment]
This is working @ppiyush13 , it had to have been this is=" -> as=" problem

**Comment by gorkamolero** [comment]
Thanks a lot for the hard work, anything you need for testing just let me know

**Comment by gorkamolero** [comment]
@ppiyush13 We're still having the gap issue on mobile safari. Any plans on addressing this?
Thank you!

**Comment by ppiyush13** [comment]
Hey @gorkamolero, I can address this issue if you provide some reproducible repository and provide some bit of information on how you are using this library

1. React framework you are using
2. Code snippet around error scenarios
3. OS version, browser version, `styled-components` version, `react` version

Thanks reporting issue

**Comment by gorkamolero** [comment]
Hi @ppiyush13 I'm sorry it must have been an issue with the wrap property. Please ignore

**Comment by ppiyush13** [comment]
Stable version `2.0.0` is released. Please go through readme file to check breaking changes and enhancements.
